// Code generated by ogen, DO NOT EDIT.
package openapi

type AccountStatusRes interface {
	accountStatusRes()
}

type CreateProjectRes interface {
	createProjectRes()
}

type DeleteAccountRes interface {
	deleteAccountRes()
}

type GetProjectByIdRes interface {
	getProjectByIdRes()
}

type GetUserByIdRes interface {
	getUserByIdRes()
}

type GetUserByNameRes interface {
	getUserByNameRes()
}

type ListProjectsRes interface {
	listProjectsRes()
}

type ListUsersRes interface {
	listUsersRes()
}

type LoginAccountRes interface {
	loginAccountRes()
}

type LogoutAccountRes interface {
	logoutAccountRes()
}

type RefreshTokenRes interface {
	refreshTokenRes()
}

type RegisterAccountRes interface {
	registerAccountRes()
}
