// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AccountStatus implements accountStatus operation.
//
// Retrieve account status.
//
// GET /api/v1/auth/status
func (UnimplementedHandler) AccountStatus(ctx context.Context) (r AccountStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProject implements createProject operation.
//
// Create project.
//
// POST /api/v1/projects
func (UnimplementedHandler) CreateProject(ctx context.Context, req *CreateProjectReq) (r CreateProjectRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAccount implements deleteAccount operation.
//
// Delete the authenticated account and it's data.
//
// DELETE /api/v1/auth/delete
func (UnimplementedHandler) DeleteAccount(ctx context.Context) (r DeleteAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProjectById implements getProjectById operation.
//
// Find project by ID.
//
// GET /api/v1/projects/{projectID}
func (UnimplementedHandler) GetProjectById(ctx context.Context, params GetProjectByIdParams) (r GetProjectByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserById implements getUserById operation.
//
// Find user by ID.
//
// GET /api/v1/users/{userID}
func (UnimplementedHandler) GetUserById(ctx context.Context, params GetUserByIdParams) (r GetUserByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserByName implements getUserByName operation.
//
// Find user by username.
//
// GET /api/v1/users/name/{username}
func (UnimplementedHandler) GetUserByName(ctx context.Context, params GetUserByNameParams) (r GetUserByNameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProjects implements listProjects operation.
//
// List projects.
//
// GET /api/v1/projects
func (UnimplementedHandler) ListProjects(ctx context.Context) (r ListProjectsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListUsers implements listUsers operation.
//
// List users.
//
// GET /api/v1/users
func (UnimplementedHandler) ListUsers(ctx context.Context) (r ListUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LoginAccount implements loginAccount operation.
//
// Generate and fetch auth token.
//
// POST /api/v1/auth/login
func (UnimplementedHandler) LoginAccount(ctx context.Context, req *LoginAccountReq) (r LoginAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LogoutAccount implements logoutAccount operation.
//
// Revoke authentication token.
//
// POST /api/v1/auth/logout
func (UnimplementedHandler) LogoutAccount(ctx context.Context) (r LogoutAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RefreshToken implements refreshToken operation.
//
// Refresh authentication token.
//
// POST /api/v1/auth/refresh
func (UnimplementedHandler) RefreshToken(ctx context.Context) (r RefreshTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RegisterAccount implements registerAccount operation.
//
// Register a new account.
//
// POST /api/v1/auth/register
func (UnimplementedHandler) RegisterAccount(ctx context.Context, req *RegisterAccountReq) (r RegisterAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}
